@startuml
title Text Util
hide footbox
skinparam monochrome true

Client -> Server: HTTP Request
note right: POST /util/text/lowercase HTTP/1.1\n\n{\n  "input": "Lorem Ipsum"\n}
Server -> Client: HTTP Response
note left: HTTP/1.1 200 OK\n\n{\n  "action": "lowercase",\n  "input": "Lorem Ipsum",\n  "output": "lorem ipsum"\n}
@enduml
