@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Exam {
  -weight: Weight
  -answer: Answer
  -exams: Array<Answer>
  +__construct(answer: Answer, weight: Weight)
  +add(exam: Answer): void
  +avg(): float
  +min([count: float]): Array<float>
  +max([count: float]): Array<float>
  +lt([limit: float]): Array<float>
  +gt([limit: float]): Array<float>
}
@enduml
