@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class Exam {
  -weight: Array<int>
  -answer: Array<string>
  -answers: Array<string, string>
  -grades: Array<float>
  +__construct(answer, weight)
  +add(student, answer): voind
  +grade(student): float
  +avg(): float
  +min([count: float]): Array<int>
  +max([count: float]): Array<int>
  +lt([limit: float]): Array<int>
  +gt([limit: float]): Array<int>
}
@enduml